# Generated by Django 3.2.8 on 2022-05-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('follower', '0002_fallower_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallower',
            name='liked_articles',
            field=models.ManyToManyField(blank=True, to='blog.Article'),
        ),
    ]
